git:
  depth: 1

branches:
  only:
    - master

language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - libsdl2-dev
            - ninja-build
            - cmake
            - libvlc-dev
            - libvlccore-dev
    - os: osx
      osx_image: xcode11.3
      compiler: clang++
      addons:
        homebrew:
          packages:
            - sdl2
            - ninja
          update: true

script:
  - mkdir build; cd build;
    if [ $TRAVIS_OS_NAME == linux ]; then cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=libADLMIDI -DWITH_MIDIPLAY=ON -DWITH_OLD_UTILS=ON -DWITH_GENADLDATA=OFF -DWITH_CPP_EXTRAS=ON -DWITH_ADLMIDI2=ON -DEXAMPLE_SDL2_AUDIO=ON -DWITH_VLC_PLUGIN=ON -DVLC_PLUGIN_NOINSTALL=ON -DlibADLMIDI_SHARED=ON -DlibADLMIDI_STATIC=ON -DWITH_UNIT_TESTS=ON ..; fi;
    if [ $TRAVIS_OS_NAME == osx ]; then cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=libADLMIDI -DWITH_MIDIPLAY=OFF -DWITH_OLD_UTILS=ON -DWITH_GENADLDATA=OFF -DWITH_CPP_EXTRAS=ON -DWITH_ADLMIDI2=OFF -DEXAMPLE_SDL2_AUDIO=OFF -DWITH_VLC_PLUGIN=OFF -DVLC_PLUGIN_NOINSTALL=ON -DlibADLMIDI_SHARED=ON -DlibADLMIDI_STATIC=ON -DWITH_UNIT_TESTS=ON ..; fi;
  - cmake --build . --config Release

